# Prod environment
variables:

  # Global
  ap_vm_image: ubuntu-20.04

  namespace: demoworkspace # Updated namespace
  postfix: 001 # Updated postfix
  location: eastus # Updated location

  environment: prod
  enable_aml_computecluster: true
  enable_aml_secure_workspace: true
  enable_monitoring: false

  # Azure DevOps
  ado_service_connection_rg: Azure-ARM-Prod-ChurnIndustry
  ado_service_connection_aml_ws: Azure-ARM-Prod-ChurnIndustry

  # DO NOT TOUCH

  # For pipeline reference
  resource_group: gl-oct24-pro
  aml_workspace: gl-oct24-pro
  application_insights: gloct24pro1091352697
  key_vault: gloct24pro5504447425
  container_registry: e067b59337b64135ae9fb0fc25d04f1a
  storage_account: gloct24pro9428723566
  
  # # For terraform reference
  # terraform_version: 0.14.7
  # terraform_workingdir: infrastructure
  # terraform_st_resource_group: rg-$(namespace)-$(postfix)$(environment)-tf
  # terraform_st_location: $(location)
  # terraform_st_storage_account: st$(namespace)$(postfix)$(environment)tf
  # terraform_st_container_name: default
  # terraform_st_key: mlops-tab
